# Generated by Django 4.0.3 on 2022-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_alter_user_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famous',
            name='category',
            field=models.IntegerField(choices=[(0, 'Places'), (1, 'Food'), (2, 'Collectibles')], default=0, max_length=1),
        ),
    ]
