# Generated by Django 4.0.3 on 2022-03-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_alter_famous_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famous',
            name='category',
            field=models.IntegerField(choices=[(0, 'Places'), (1, 'Food'), (2, 'Collectibles')], default=0),
        ),
        migrations.AlterField(
            model_name='famous',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.location'),
        ),
    ]
