# Generated by Django 4.0.3 on 2022-03-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_alter_famous_category_alter_famous_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='famous',
            options={'verbose_name': 'Famous', 'verbose_name_plural': 'Famous'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
