# Generated by Django 4.0.3 on 2022-03-20 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_alter_famous_options_alter_location_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famous',
            name='dislike',
        ),
        migrations.AddField(
            model_name='famous',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='famous',
            name='like',
        ),
        migrations.AddField(
            model_name='famous',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
