# Generated by Django 4.0.3 on 2022-03-24 08:52

import ckeditor.fields
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_remove_famous_dislike_famous_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='famous',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='famous',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
