# Generated by Django 4.0.3 on 2022-03-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_famous_description_famous_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='famous',
            name='dislikeint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='famous',
            name='likeint',
            field=models.IntegerField(default=0),
        ),
    ]
